webproject/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'


urlpatterns = [
    path('',views.feed, name="feed"),
    path('addphoto/', views.addphoto, name="addphoto"),
    path('signup/', views.signup, name="signup"),
    path('profilecustomization/', views.profilecustomization, name="profilecustomization" ),
    path('profileupdate/', views.update_profile, name="profileuptade" ),
    path('userprofile/', views.userprofile, name="userprofile" ),
    path('deletephoto/<int:id>', views.deletephoto, name="deletephoto"),
    path('search/', views.search, name="search"),
    path('post_detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('searchprofile/', views.search_profile, name="searchprofile" ),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('user_selected_profile/<int:id>', views.user_selected_profile, name='user_selected_profile')
]

webproject/webproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static


urlpatterns = [
    path('',include('webapp.urls')),
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),




]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webproject/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class WebAppModel(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to="images/")
    description = models.TextField(max_length=200)  
    
    def __str__(self):
        return f"Username: {self.username} Description: {self.description}, Image: {self.image}"

class UserProfile(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500 ,blank=True)
    profile_picture = models.ImageField(upload_to="profilepics/", blank=True, null=True)
    hobies = models.TextField(max_length=500, null=True)

    def __str__(self):
        return f"Username: {self.username} Bio: {self.bio}, ProfilePic: {self.profile_picture}, Hobies: {self.hobies}"
    # def __str__(self):
    #     return self.user.username

class UserComments(models.Model):
    comment = models.TextField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    web_app_model = models.ForeignKey(WebAppModel, on_delete=models.CASCADE)
    
    def __str__(self) :
        return f"comment{self.comment}, user: {self.user}, web_app_model: {self.web_app_model}"
    

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(WebAppModel, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} liked {self.post}"  
     
    @classmethod
    def like_count(cls, post):
        return cls.objects.filter(post=post).count()

webproject/webapp/forms.py
from django import forms
from .models import WebAppModel, UserProfile, UserComments
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class AddPhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # User'ı kwargs'tan çıkartıp class attribute olarak sakla
        self.user = kwargs.pop('user', None)
        super(AddPhotoForm, self).__init__(*args, **kwargs)

    class Meta:
        model = WebAppModel
        fields = ["image", "description"]

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class UserCustimizationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UserCustimizationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserProfile
        fields =  ["bio","profile_picture","hobies"]

class UserProfileUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UserProfileUpdateForm, self).__init__(*args, **kwargs)

    # def save(self, commit=True):
    #     instance = super(UserProfileUpdateForm, self).save(commit=False)
    #     instance.user = self.user
    #     if commit:
    #         instance.save()
    #     return instance


    class Meta:
        model = UserProfile
        fields = ["bio","profile_picture","hobies"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = UserComments
        fields = ['comment']

webproject/webapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from .forms import AddPhotoForm, SignUpForm, UserCustimizationForm, UserProfileUpdateForm, CommentForm
from . import models
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.

@login_required(login_url="/login")
def index(request):
    pass

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse("webapp:profilecustomization"))
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

@login_required(login_url="/login")
def profilecustomization(request):

    if request.method == "POST":
        form = UserCustimizationForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            post = form.save(commit=False)
            post.username = request.user
            post.save()
            return redirect(reverse('webapp:feed'))
        else:
            print(form.errors)
    else:
        form = UserCustimizationForm()
        
    return render(request, "webapp/usercustimization.html", context={"form": form})

def update_profile(request):
    user_profile = request.user.userprofile  # Kullanıcının profil örneğini al
    if request.method == "POST":
        form = UserProfileUpdateForm(request.POST, request.FILES, instance=user_profile )
        if form.is_valid():
            form.save()
            return redirect(reverse('webapp:feed'))  # Profil sayfasına yönlendir
    else:
        form = UserProfileUpdateForm(instance=user_profile)

    return render(request, "webapp/userupdate.html", context={"form": form})    


@login_required(login_url="/login")
def addphoto(request):

    if request.method == "POST":
        # Formu oluştururken request.user'ı iletebilirsiniz
        form = AddPhotoForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            # Formu kaydetmeden önce user alanını doldur
            post = form.save(commit=False)
            post.username = request.user
            post.save()
            return redirect(reverse('webapp:feed'))
        else:
            print(form.errors)
    else:
        form = AddPhotoForm()

    return render(request, "webapp/addphoto.html", context={"form": form})

@login_required(login_url="/login")
def deletephoto(request, id):
    deleted_posts = models.WebAppModel.objects.get(pk = id)
    if request.user == deleted_posts.username:
        models.WebAppModel.objects.filter(id=id).delete()
        return redirect(reverse('webapp:feed'))
        

def feed(request):

    posts = models.WebAppModel.objects.all()
    context = {"posts":posts}
    print(posts.values)
    return render(request, "webapp/feed.html", context=context)


@login_required(login_url="/login")
def userprofile(request):
    user_posts = models.WebAppModel.objects.filter(username=request.user)
    context = {'user_posts': user_posts}
    return render(request, 'webapp/userprofile.html', context=context)

def user_selected_profile(request, id):
    user_posts = models.WebAppModel.objects.filter(username = id)
    context = {'user_posts': user_posts}
    return render(request, 'webapp/user_selected_profile.html', context=context)

def search(request):
    if request.method == 'POST':
        print(request.POST["search"])
        user_keyword = request.POST["search"]
        queryset = models.WebAppModel.objects.filter(
            Q(description = user_keyword)|
            Q(description__contains = user_keyword)|
            Q(description__icontains = user_keyword)|
            Q(description__startswith=user_keyword)|
            Q(description__endswith=user_keyword)|
            Q(description__in=[user_keyword])                              
                                                                                              )   
        
        print('--QUERYSET--',queryset.all())
        return render(request,'webapp/searchresults.html', context={'queryset':queryset})
    
def search_profile(request):

    if request.method == 'POST':
        print(request.user)
        user_keyword = request.POST["search"]
        queryset = models.WebAppModel.objects.filter(username=request.user).filter(
                Q(description = user_keyword)|
                Q(description__contains = user_keyword)|
                Q(description__icontains = user_keyword)|
                Q(description__startswith=user_keyword)|
                Q(description__endswith=user_keyword)|
                Q(description__in=[user_keyword])         
        )
        return render(request,'webapp/searchresults.html', context={'queryset':queryset})

        

    
@login_required(login_url="/login")
def post_detail(request, post_id):
    post = get_object_or_404(models.WebAppModel, id=post_id)
    comments = post.usercomments_set.all()

    like_count = models.Like.like_count(post)
    likers = models.Like.objects.filter(post=post).values_list('user__username', flat=True)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            user = request.user
            models.UserComments.objects.create(comment=comment, user=user, web_app_model=post)
            return redirect('webapp:post_detail', post_id=post_id)
    else:
        form = CommentForm()
    
    return render(request, 'webapp/post_detail.html', {'post': post, 'comments': comments, 'form': form, 'like_count': like_count, 'likers': likers})


def like_post(request, post_id):
    post = get_object_or_404(models.WebAppModel, id=post_id)

    if models.Like.objects.filter(user=request.user, post=post).exists():
        pass
    else:
        models.Like.objects.create(user=request.user, post=post)

    like_count = models.Like.like_count(post)

    post_detail_url = reverse('webapp:post_detail', kwargs={'post_id': post_id})
    post_detail_url += f'?like_count={like_count}'
    return redirect(post_detail_url)

webproject/webapp/templates/webapp/addphoto.html
{% extends "base.html" %}
{% block content %}

<form action="{% url 'webapp:addphoto' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Photo</button>
</form>

{% endblock  %}

webproject/webapp/templates/webapp/feed.html
{% extends 'base.html' %}
{% load static %}


{%block content%}

<form class="d-flex" role="search" method="post" action="{% url 'webapp:search' %}">
    {% csrf_token %}
    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>


{% for post in posts %}
<a href=" {%url 'webapp:user_selected_profile' post.username.id%} "><div style="color: blueviolet;">{{post.username}}</div></a>
<a href="{% url 'webapp:post_detail' post.id %}">
    <div class="post-card">
    <div class="post-container">
        <img src="{{ post.image.url }}" alt="post_image" srcset="{{ post.image.url }} 320w, {{ post.image.url }} 640w, {{ post.image.url }} 1280w">
        <p class="post-description">{{ post.description }}</p>
    </div>
    </div>  
</a>
{% if post.username == user %}
    <a href="{% url 'webapp:deletephoto' post.id %}" class="btn btn-danger">Delete</a>
{% endif %}
{% endfor %}


{%endblock%}

webproject/webapp/templates/webapp/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Ana Sayfa</h1>

{% endblock %}

webproject/webapp/templates/webapp/post_detail.html
{% extends "base.html" %}
{% block content %}
<div class="post-detail-container">
    <!-- post_detail.html -->
    <div class="post-detail-image-container">
        <h2>{{ post.description }}</h2>
        <img src="{{ post.image.url }}" alt="{{ post.description }}" class="post-detail-image">
    </div>

    <div class="post-detail-comments">
        <h3>Beğeniler: {{ like_count }}</h3>
        <p>Beğenenler: {{ likers|join:", " }}</p>
        
        <!-- Like butonu -->
        <form method="post" action="{% url 'webapp:like_post' post_id=post.id %}">
            {% csrf_token %}
            <button type="submit"><span class="heart">&#x2665;</span> Beğen</button>
        </form>

        <h3>Yorumlar</h3>
        {% for comment in comments %}
            <p>{{ comment.user.username }}: {{ comment.comment }}</p>
        {% endfor %}

        <!-- Yorum formunu göster -->
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'webapp:post_detail' post_id=post.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Yorum Yap</button>
            </form>
        {% else %}
            <p>Yorum yapabilmek için giriş yapmalısınız.</p>
        {% endif %}
    </div>
</div>
{% endblock  %}

webproject/webapp/templates/webapp/searchresults.html
{% extends 'base.html' %}
{% load static %}


{%block content%}

{% for post in queryset %}
<a href="{% url 'webapp:post_detail' post.id %}">
    <div style="color: blueviolet;">{{post.username}}</div>
    <div class="post-container" onclick="showDetails('{{ post.image.url }}', '{{ post.description }}')">
        <img src="{{ post.image.url }}" alt="post_image" srcset="{{ post.image.url }} 320w, {{ post.image.url }} 640w, {{ post.image.url }} 1280w">
        <p class="post-description">{{ post.description }}</p>
    </div>
    </a>
    {% if post.username == user %}

    <a href="{% url 'webapp:deletephoto' post.id %}" class="btn btn-danger">Delete</a>

    
    {% endif %}
{% endfor %}


{%endblock%}

webproject/webapp/templates/webapp/user_selected_profile.html
{% extends 'base.html' %}
{% load static %}


{%block content%}

<form class="d-flex" role="search" method="post" action="{% url 'webapp:searchprofile' %}">
    {% csrf_token %}
    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>

{% for post in user_posts %}
<a href="{% url 'webapp:post_detail' post.id %}">
<div style="color: blueviolet;">{{post.username}}</div>
<div class="post-container" onclick="showDetails('{{ post.image.url }}', '{{ post.description }}')">
    <img src="{{ post.image.url }}" alt="post_image" srcset="{{ post.image.url }} 320w, {{ post.image.url }} 640w, {{ post.image.url }} 1280w">
    <p class="post-description">{{ post.description }}</p>
</div>
</a>

{% if post.username == user %}

    <a href="{% url 'webapp:deletephoto' post.id %}" class="btn btn-danger">Delete</a>

    
    {% endif %}

{% endfor %}

{%endblock%}

webproject/webapp/templates/webapp/usercustimization.html
{% extends "base.html" %}
{% block content %}
    <div>                    
                   
                <form action="{% url 'webapp:profilecustomization' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}

   
                    {{form.as_p}}
                    <button type="submit">Tamam</button>  
 
    </form>
    </div>

{% endblock %}

webproject/webapp/templates/webapp/userprofile.html
{% extends 'base.html' %}
{% load static %}


{%block content%}

<form class="d-flex" role="search" method="post" action="{% url 'webapp:searchprofile' %}">
    {% csrf_token %}
    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>

{% for post in user_posts %}
<a href="{% url 'webapp:post_detail' post.id %}">
<div style="color: blueviolet;">{{post.username}}</div>
<div class="post-container" onclick="showDetails('{{ post.image.url }}', '{{ post.description }}')">
    <img src="{{ post.image.url }}" alt="post_image" srcset="{{ post.image.url }} 320w, {{ post.image.url }} 640w, {{ post.image.url }} 1280w">
    <p class="post-description">{{ post.description }}</p>
</div>
</a>

{% if post.username == user %}

    <a href="{% url 'webapp:deletephoto' post.id %}" class="btn btn-danger">Delete</a>

    
    {% endif %}

{% endfor %}

{%endblock%}

webproject/webapp/templates/webapp/userupdate.html
{% extends "base.html" %}
{% block content %}

<h2>Profil Güncelleme</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Güncelle</button>
</form>


{% endblock  %}