webproject/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'


urlpatterns = [
    path('',views.feed, name="feed"),
    path('addphoto/', views.addphoto, name="addphoto"),
    path('signup/', views.signup, name="signup"),
    path('profilecustomization/', views.profilecustomization, name="profilecustomization" ),
    path('profileupdate/', views.update_profile, name="profileuptade" ),
    path('userprofile/', views.userprofile, name="userprofile" ),
    path('deletephoto/<int:id>', views.deletephoto, name="deletephoto"),
    path('search/', views.search, name="search"),
    path('post_detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('searchprofile/', views.search_profile, name="searchprofile" ),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('user_selected_profile/<int:id>', views.user_selected_profile, name='user_selected_profile')
]

webproject/webproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static


urlpatterns = [
    path('',include('webapp.urls')),
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),




]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Artist Social{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    <!-- Diğer stiller buraya eklenir -->
    <link rel="stylesheet" href="{% static 'css/feed.css' %}">
    <link rel="stylesheet" href="{% static 'css/post_detail.css' %}">

    

    
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Artist Social</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                
                {% comment %} <form class="d-flex" role="search" method="post" action="{% url 'webapp:search' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form> {% endcomment %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'webapp:feed' %}">Feed</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webapp:userprofile' %}">Profil</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'webapp:addphoto' %}">Add Photo</a>
                        </li>
                    </li>

                {% endif %}
               
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                
                        {% if user.userprofile.profile_picture %}
                            <li class="nav-item">
                                <img src="{{ user.userprofile.profile_picture.url }}" alt="Profile Picture" class="rounded-circle" width="40" height="40">
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Windows_10_Default_Profile_Picture.svg/2048px-Windows_10_Default_Profile_Picture.svg.png" alt="Default Profile Picture" class="rounded-circle" width="30" height="30">
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'webapp:profileuptade' %}">Edit Your Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
                        </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Bootstrap JS ve Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.8/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Diğer scriptler buraya eklenir -->
</body>
</html>